TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += DG645.db
DB += Output.db
DB += Channel.db
DB += DG645.proto

#=======================================
include $(TOP)/configure/RULES
